fix: remove unused images

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -43,13 +43,14 @@ jobs:
           scp -o StrictHostKeyChecking=no -i key.pem env $EC2_USER@$EC2_HOST:/path/on/ec2/env
           echo "Begin ssh"
           ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
-            echo "Pulling Docker image..."
-            docker pull ${DOCKER_HUB_USERNAME}/nestjs-app:latest || { echo "Failed to pull image"; exit 1; }
-            echo "Stopping old container..."
             docker stop nestjs-app || true
             echo "Removing old container..."
             docker rm nestjs-app || true
             echo "Starting new container..."
+            docker rmi ${DOCKER_HUB_USERNAME}/nestjs-app:latest -f || true
+            echo "Pulling Docker image..."
+            docker pull ${DOCKER_HUB_USERNAME}/nestjs-app:latest || { echo "Failed to pull image"; exit 1; }
+            echo "Stopping old container..."
             docker run --env-file /path/on/ec2/env -d --name nestjs-app -p 3000:3000 ${DOCKER_HUB_USERNAME}/nestjs-app:latest
           EOF
           echo "Finish ssh"
