Update backend.yml

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -44,13 +44,13 @@ jobs:
           echo "Begin ssh"
           ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
             echo "Pulling Docker image..."
-            docker pull maikusobu/nestjs-app:latest || { echo "Failed to pull image"; exit 1; }
+            docker pull ${DOCKER_HUB_USERNAME}/nestjs-app:latest || { echo "Failed to pull image"; exit 1; }
             echo "Stopping old container..."
             docker stop nestjs-app || true
             echo "Removing old container..."
             docker rm nestjs-app || true
             echo "Starting new container..."
-            docker run --env-file /path/on/ec2/env -d --name nestjs-app -p 3000:3000 maikusobu/nestjs-app:latest
+            docker run --env-file /path/on/ec2/env -d --name nestjs-app -p 3000:3000 ${DOCKER_HUB_USERNAME}/nestjs-app:latest
           EOF
           echo "Finish ssh"
           rm key.pem env
